language: php

php:
    - 7.0
    - 7.1

env:
    - SYMFONY_VERSION=3.3.*
    - SYMFONY_VERSION=dev-master

matrix:
    allow_failures:
        - env: SYMFONY_VERSION=dev-master

before_script:
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    # This command must be run with `--prefer-source`, otherwise the `Doctrine\Tests\OrmTestCase` class
    #Â won't be found.
    - composer update --prefer-source

script:
  - phpunit --coverage-text
