language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 7.0
    - 7.1

env:
  global:
    - TEST_COMMAND="composer test"
  matrix:
    - SYMFONY_VERSION=3.3.*

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.1
      env: SYMFONY_VERSION=4.0.*
  include:
    - php: 7.0
      env: TEST_COMMAND="composer test-ci" COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_VERSION=3.3.* COVERAGE=true
    - php: 7.0
      env: TEST_COMMAND="phpunit --testsuite doctrine" COMPOSER_FLAGS="--prefer-source" SYMFONY_VERSION="3.3.* phpunit/phpunit:^5.7"
    - php: 7.1
      env: SYMFONY_VERSION=4.0.*

before_script:
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    # This command must be run with `--prefer-source`, otherwise the `Doctrine\Tests\OrmTestCase` classÂ won't be found.
    - composer update $COMPOSER_FLAGS

script:
    - $TEST_COMMAND

after_success:
    - if [[ $COVERAGE = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ $COVERAGE = true ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi
